Algoritmo "Exercicios da aula 06 conversor de temperatura "

// Algoritmo que faz a conversao da temperatura de fahrenheit para celsius

Var

         fahrenheit, celsius :REAL

Inicio

             ESCREVA("Qual e a temperatura em fahrenheit ")
             lEIA(fahrenheit)
             celsius <- (fahrenheit -32) / 1.8
             ESCREVA("A conversao da temperatura de fahrenheit para celsius e ", celsius:4:1)

Fimalgoritmo